discourse_custom_topic_lists:
  discourse_custom_topic_lists_enabled:
    default: false
    client: true
  custom_topic_lists:
    client: true
    default: >-
      [
        {
          "icon": "question",
          "name": "New questions",
          "bannerLabel": "Topic for new questions",
          "path": "some-long-path-for-questions",
          "query": "category:questions",
          "showOnSidebar": true,
          "access": ""
        },
        {
          "icon": "discourse-sparkles",
          "name": "Arts and Media",
          "bannerLabel": "Topic with categories related to arts and media",
          "path": "arts-and-media",
          "query": "category:arts-media",
          "showOnSidebar": true,
          "access": ""
        }
      ]
    json_schema: DiscourseCustomTopicLists::SiteSettings::CustomTopicsSchema