discourse_custom_topic_lists:
  discourse_custom_topic_lists_enabled:
    default: false
    client: true
  custom_topic_lists:
    client: false
    default: >-
      []
    json_schema: DiscourseCustomTopicLists::SiteSettings::CustomTopicsSchema